CREATE TABLE IF NOT EXISTS todos (
  id BIGSERIAL PRIMARY KEY,
  text TEXT NOT NULL,
  done BOOLEAN NOT NULL DEFAULT FALSE,
  category TEXT NOT NULL DEFAULT 'Umum',
  deadline DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
